### ISSUE TITLE
Turn this into a package?

### ISSUE THREAD

**Issue by seanbreckenridge** [deepjyoti30/downloader-cli#1]
Display is very cool, but having an alias/copying `download.py` to whatever directory you want to use it it in is fiddly, especially in big projects.

It would be easier if this was installed using [setuptools](https://pythonhosted.org/an_example_pypi_project/setuptools.html), which would automatically install `urllib3`, and create the `dw` console script regardless of OS. (so no need to create the alias)

If it was installed into the global python packages, one could use it anywhere, by doing something like

`pip3 install --user git+https://github.com/deepjyoti30/downloader-cli`

and then importing it like any other package you'd install with pip.

If this seems like something you'd want to do, I can create a PR.

**Comment by deepjyoti30** [comment]
Hey @seanbreckenridge the reason I didn't make it a package was I thought it won't be used by so many people. I sure would love to push it to Pypi.

If you want to make a PR, go ahead and do that, I'll review it whenever I get the time to do so. Thanks!

**Comment by rhysperry111** [comment]
I might have a look into submitting it to the AUR. Sorry if you're not using Arch.
BTW I use Arche

**Comment by seanbreckenridge** [comment]
@deepjyoti30 

[Heres](https://github.com/seanbreckenridge/downloader-cli/commit/84717fb1b46fcee57bb72867b6972c454182aab4) the basic one I came up with.

Few issues that I'm not sure how you'd like to resolve.

Since the script is currently only the `download.py` file, I've treated that as its own module using `py_modules`, as that retains the ability to simply copy the `download.py` and doesnt change the structure much (you can still do `from download import Download` from anywhere once its installed into the global site-packages).

However, `download` isn't available on PyPi. I think the sanest way to do this would be to create a folder (package) called `download_cli` and put `download.py` there, with a `__init__.py` file that does:

```
from .download import Download
```

and change the entry point to:

```

    entry_points={
        'console_scripts': [
            "dw = download_cli.download:main"
        ]
    }, 
```

That way after its installed into the global site-packages its imported like `from download_cli import Download`.

Thoughts?

**Comment by deepjyoti30** [comment]
@rhysperry111 BTW, I use Arch too.

**Comment by deepjyoti30** [comment]
Hey @seanbreckenridge  I thought it was clear when I asked you to make it a package that you'd have tl change the name too. I'm okay with going with ```download_cli``` or ```downloader_cli``.

BTW If you are busy, I can make the package since I seem to have some time to spare today. Would you be okay with that?

**Comment by seanbreckenridge** [comment]
Sure, I am somewhat busy, so you making the package sounds good to me, feel free to copy whatever I had or not.

**Comment by deepjyoti30** [comment]
@seanbreckenridge I'll push the package soon.

**Comment by deepjyoti30** [comment]
@seanbreckenridge Uploaded the package to PyPi. Closing this issue.
