### ISSUE TITLE
ERROR: Errno 22 on instagram pictures

### ISSUE THREAD

**Issue by matze19999** [deepjyoti30/downloader-cli#11]
If I try to download a picture from instagram I get errno 22.

For example if I try to download the picture from this url:

https://scontent-muc2-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/138734412_2824463591207841_3866668501561580560_n.jpg?_nc_ht=scontent-muc2-1.cdninstagram.com&_nc_cat=109&_nc_ohc=KyByhjfBR1cAX9pp60k&tp=1&oh=c6072950e86196c504ac446f885378f3&oe=6037334E

I get following error:

ERROR: [Errno 22] Invalid argument: '138734412_2824463591207841_3866668501561580560_n.jpg?_nc_ht=scontent-muc2-1.cdninstagram.com&_nc_cat=109&_nc_ohc=KyByhjfBR1cAX9pp60k&tp=1&oh=c6072950e86196c504ac446f885378f3&oe=6037334E'

I think it tries to get the filename and splits the url wrong?

UPDATE: Only happens on Python3 installed on Windows 10. On my linux machine it runs without an error.

**Comment by ChanceNCounter** [comment]
What's the resulting filename on Linux? I'm thinking you're right about splitting the URL, as that's exactly how it gets the filename in general.

I wonder if it works on Windows when you specify the output file.

**Comment by matze19999** [comment]
The resulting filename on linux is:

"138734412_2824463591207841_3866668501561580560_n.jpg?_nc_ht=scontent-muc2-1.cdninstagram.com&_nc_cat=109&_nc_ohc=00XM2nnB6DEAX9XKqHo&tp=1&oh=3355ae5a3a6b1efee299c576b7cab446&oe=603B27CE"

And yes, it is working if I specify the output filename.

**Comment by deepjyoti30** [comment]
@ChanceNCounter @matze19999 So it seems like something is wrong with how the URL is being split on Windows.

I think I can make some changes to replace special characters with something like an underscore or a period which would work fine with Windows, I'm assuming.

**Comment by ChanceNCounter** [comment]
It's a tall order, but the ideal solution would *probably* be to cut if off at the last known extension, unless it doesn't have any extensions.

That parser wouldn't be the death of me, but I wouldn't wish it on anybody who doesn't write parsers for fun, and I'm not about to dive in. Maybe there's a module with a dict of, like, every known extension, or maybe it would have to be "the last segment is the portion of the URL between the final `.` and the next special character."

**Comment by deepjyoti30** [comment]
@ChanceNCounter your solution totally makes sense. One thing we can do is just check the URL for `?` which in an URL means the start of queries and after that character we can discard everything. That way the below URL:

`138734412_2824463591207841_3866668501561580560_n.jpg?_nc_ht=scontent-muc2-1.cdninstagram.com&_nc_cat=109&_nc_ohc=00XM2nnB6DEAX9XKqHo&tp=1&oh=3355ae5a3a6b1efee299c576b7cab446&oe=603B27CE`

would become:

`138734412_2824463591207841_3866668501561580560_n.jpg`

**Comment by matze19999** [comment]
Sounds like a great solution

**Comment by ChanceNCounter** [comment]
Yeah, I think cutting at `?` should cover the overwhelming majority of cases. Good thought.

**Comment by deepjyoti30** [comment]
@ChanceNCounter @matze19999 Should be fixed in 397397e

**Comment by matze19999** [comment]
Works perfectly, thanks
