### ISSUE TITLE
Robust tests

### ISSUE THREAD

**Issue by ChanceNCounter** [deepjyoti30/downloader-cli#15]
Now that GitHub Actions are free, depending on the storage situation, it might be possible to run pytest on push/PR. Also to have it try each invocation in succession, against a checksum (download, check integrity, delete, download, interrupt, resume, check integrity...)

**Comment by deepjyoti30** [comment]
@ChanceNCounter Those tests do sound tempting, however I will have to take a look if those would be possible on GitHub actions.

I mean, I am not sure about interrupting the downloads etc. But yeah, tests are totally something we need to add.!

**Comment by ChanceNCounter** [comment]
Without putting too much thought into it, I think the interruption could be done by Popening a medium-size download and immediately killing the process, but that's putting a lot of faith in fast computing =P

**Comment by deepjyoti30** [comment]
I think, however, we could perhaps use `Popen` and then sleep a while and then kill the process?! I am not sure if popen allows killing a process after a while.

**Comment by ChanceNCounter** [comment]
Process is a process, no?

**Comment by deepjyoti30** [comment]
@ChanceNCounter I have added an workflow to run tests whenever a push/pull request is made to the master branch. I will try to add more tests soon!
