### ISSUE TITLE
Filesize check on line 76 can fail on missing Content-Length header

### ISSUE THREAD

**Issue by ChanceNCounter** [deepjyoti30/downloader-cli#2]
I don't know much more about it than the person on reddit knew, but I thought I'd document this here. Some download requests don't get `Content-Length`, causing a TypeError exception on [line 76](https://github.com/deepjyoti30/downloader-cli/blob/0bf538e268544aac2beab0f4bd42808f29a5605f/download.py#L76). I was able to reproduce this by attempting to download `download.py` directly from this repo (via the raw content link.)

**Comment by deepjyoti30** [comment]
@ChanceNCounter Thanks for the heads up. I'll fix it soon.

**Comment by deepjyoti30** [comment]
Should be fixed now.
