### ISSUE TITLE
Feature Request : Read URLs From an input file.

### ISSUE THREAD

**Issue by Chronigan** [deepjyoti30/downloader-cli#5]
It would be very useful to be able to pass a file with urls to this and have it go through and download them.

**Comment by deepjyoti30** [comment]
@Chronigan Lemme see what I can do.

**Comment by deepjyoti30** [comment]
@Chronigan Just added it in 135f71a. Try installing the latest commits and report back here if you face any errors.

Instead of URL, a file containing URL's with every URL in a new line can be passed.

**Comment by Chronigan** [comment]
I have installed the latest version. It opens the list of files to download and after downloading the first one, it exits with the error. ERROR: File exists. See 'dw --help' for solutions.

**Comment by deepjyoti30** [comment]
@Chronigan It should be fixed now. Thanks for reporting back!

**Comment by Chronigan** [comment]
It is working great now, Thanks!

**Comment by deepjyoti30** [comment]
Added in last release
