### ISSUE TITLE
ERROR: float division by zero

### ISSUE THREAD

**Issue by jcwillox** [deepjyoti30/downloader-cli#9]
Hey, I've noticed that I often get a divide by zero error when trying to download files.
It appears the code does not handle the case when `cur_time - beg_time` is 0

```python
Traceback (most recent call last):
  File "downloader-cli\0.3.1\downloader_cli\download.py", line 376, in _download
    speed, s_unit, time_left, time_unit = self._get_speed_n_time(
  File "downloader-cli\0.3.1\downloader_cli\download.py", line 264, in _get_speed_n_time
    speed = (file_size_dl / 1024) / (cur_time - beg_time)
ZeroDivisionError: float division by zero
```

**Comment by jcwillox** [comment]
I can reliably get the error when running `dw http://speedtest.tele2.net/20MB.zip` on Windows 10, using Python 3.9.1. The issue doesn't appear to be present when using Linux.

**Comment by deepjyoti30** [comment]
@jcwillox Thanks for reporting the issue. I have, personally, never faced this error and it seems like this is something that might occur in very rare situations.

**Comment by deepjyoti30** [comment]
@jcwillox Consider checking out the commit.

**Comment by jcwillox** [comment]
@deepjyoti30 yep that's fixed the issue, thanks for sorting this out so quickly 👍

**Comment by ChanceNCounter** [comment]
It might be worth considering https://github.com/deepjyoti30/downloader-cli/compare/master...ChanceNCounter:alternate-%239 instead, to avoid running that check on every loop.

I'm not sure if that sleep is long enough - I guess I'd need to be at a Windows box to test - but it registers fine when I try

```
In [8]: def f():
   ...:     beg = time()
   ...:     sleep(0.00025)
   ...:     return time() - beg
   ...:

In [9]: (1 / 20480) / f()
Out[9]: 0.11990632318501171
```

**Comment by deepjyoti30** [comment]
@ChanceNCounter It all boils down to which way would be most effective. Based on our conversation here, we have 3 options:

- Check a condition
- Handle an exception
- Sleep for a while

Now, I don't know which one would be most cost effective and take least time. I considered going for a check instead of an exception handling since it seemed like more efficient. If sleeping is indeed worth it, we ca move to that.

**Comment by ChanceNCounter** [comment]
It will depend on the size of the file, and how long that check sequence takes in real time. Both are probably better than the exception handling approach.

**Comment by deepjyoti30** [comment]
@ChanceNCounter Cool then, let's keep the conditional for now. If that seems to throw issues, we can consider the sleep one as well.
